// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQGEZknSCHxfNud4U2jufCR3cddWwVObw',
    appId: '1:514161904272:web:9555cc4600651895186615',
    messagingSenderId: '514161904272',
    projectId: 'ai-tour-0926',
    authDomain: 'ai-tour-0926.firebaseapp.com',
    storageBucket: 'ai-tour-0926.appspot.com',
    databaseURL: 'https://ai-tour-0926-default-rtdb.firebaseio.com',
    measurementId: 'G-PWTFXEKM53',

  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm4trilVwd5jET4b8VZ00bLhvC7b3-Ycw',
    appId: '1:514161904272:android:473e3966d3567664186615',
    messagingSenderId: '514161904272',
    projectId: 'ai-tour-0926',
    storageBucket: 'ai-tour-0926.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0O4xJNsRNLBnVisA6HW511WMSFX2e7Wg',
    appId: '1:514161904272:ios:ddb82525d562905f186615',
    messagingSenderId: '514161904272',
    projectId: 'ai-tour-0926',
    storageBucket: 'ai-tour-0926.appspot.com',
    iosBundleId: 'com.example.aiTour',
  );
}
